/*
** tabs.c for strace in /home/ss814/Documents/Epitech/strace-2015-2014s-savine_s
**
** Made by Sampson SAVINEL
** Login   <ss814@epitech.net>
**
** Started on  Sun May 13 15:16:59 2012 Sampson SAVINEL
** Last update Sun May 13 22:01:51 2012 belia-_r
*/

#include	"strace.h"

t_syscall	g_syscall_tab[] =
  {
    { "read ", 0, "%d", 3, "%d, %p, %d"},
    { "write ", 1, "%d", 3, "%d, %p, %d"},
    { "open ", 2, "%d", 3, "%s, %d, %d"},
    { "close ", 3, "%d", 1, "%d"},
    { "stat ", 4, "%d", 2, "%s, %p"},
    { "fstat ", 5, "%d", 2, "%d, %p"},
    { "lstat ", 6, "%d", 2, "%s, %p"},
    { "poll ", 7, "%d", 3, "%p, %l, %d"},
    { "lseek ", 8, "%d", 3, "%d, %d, %d"},
    { "mmap ", 9, "%p", 5, "%p, %d, %d, %d, %d"},
    { "mprotect ", 10, "%d", 3, "%p, %l, %d"},
    { "munmap ", 11, "%d", 2, "%p, %l"},
    { "brk ", 12, "%d", 1, "%p"},
    { "rt_sigaction ", 13, "%d", 2, "%d, %p, %p"},
    { "rt_sigprocmask ", 14, "%d", 3, "%d, %p, %p"},
    { "rt_sigreturn ", 15, "%d", 1, "%l"},
    { "ioctl ", 16, "%d", 2, "%d, %d, ..."},
    { "pread64 ", 17, "%l", 4, "%d, %p, %l, %d"},
    { "pwrite64 ", 18, "%l", 4, "%d, %p, %l, %d"},
    { "readv ", 19, "%l", 3, "%d, %p, %d"},
    { "writev ", 20, "%l", 3, "%d, %p, %d"},
    { "access ", 21, "%d", 2, "%s, %d"},
    { "pipe ", 22, "%d", 1, "%d"},
    { "select ", 23, "%d", 5, "%d, %p, %p, %p, %p"},
    { "sched_yield ", 24, "%d", 0, ""},
    { "mremap ", 25, "%p", 4, "%p, %l, %l, %d, ..."},
    { "msync ", 26, "%d", 3, "%p, %l, %d"},
    { "mincore ", 27, "%d", 3, "%p, %l, %s"},
    { "madvise ", 28, "%d", 3, "%p, %l, %d"},
    { "shmget ", 29, "%d", 3, "%d , %l, %d"},
    { "shmat ", 30, "%p", 3, "%d, %p, %d"},
    { "shmctl ", 31, "%d", 3, "%d, %d, %p"},
    { "dup ", 32, "%d", 1, "%d"},
    { "dup2 ", 33, "%d", 2, "%d, %d"},
    { "pause ", 34, "%d", ""},
    { "nanosleep ", 35, "%d", 2, "%p, %p"},
    { "getitimer ", 36, "%d", 2, "%d, %p"},
    { "alarm ",37, "%d", 1, "%d"},
    { "setitimer ", 38, "%d", 3, "%d, %p, %p"},
    { "getpid ", 39, "%d", 0, ""},
    { "sendfile ", 40, "%l", 4, "%d, %d, %d, %d"},
    { "socket ", 41, "%d", 3, "%d, %d, %d"},
    { "connect ", 42, "%d", 3, "%d, %p, %d"},
    { "accept ", 43, "%d", 3, "%d, %p, %p"},
    { "sendto ", 44, "%l", 4, "%d, %p, %l, %d"},
    { "recvfrom ", 45, "%l", 6, "%d, %p, %l, %d, %p, %p"},
    { "sendmsg ", 46, "%l", 3, "%d, %p, %d"},
    { "recvmsg ", 47, "%l", 3, "%d, %p, %d"},
    { "shutdown ", 48, "%d", 2, "%d, %d"},
    { "bind ", 49, "%d", 3, "%d, %p, %d"},
    { "listen ", 50, "%d", 2, "%d, %d"},
    { "getsockname ", 51, "%d", 3, "%d, %p, %p"},
    { "getpeername ", 52, "%d", 3, "%d, %p, %p"},
    { "socketpair ", 53, "%d", 4, "%d, %d, %d, %d"},
    { "setsockopt ", 54, "%d", 5, "%d, %d, %d, %p, %d"},
    { "getsockopt ", 55, "%d", 5, "%d, %d, %d, %p, %p"},
    { "clone ", 56, "%d", 4, "%p, %p, %d, %p, ..."},
    { "fork ", 57, "%d", 0, ""},
    { "vfork ", 58, "%d", 0, ""},
    { "execve ", 59, "%d", 3, "%s, %p, %p"},
    { "exit ", 60, "", 1, "%d"},
    { "wait4 ", 61, "%d", 4, "%d, %p, %d, %p"},
    { "kill ", 62, "%d", 2, "%d, %d"},
    { "uname ", 63, "%d", 1, "%p"},
    { "semget ", 64, "%d", 3, "%d, %d, %d"},
    { "semop ", 65, "%d", 3, "%d, %p, %d"},
    { "semctl ", 66, "%d", 3, "%d, %d, %d, ..."},
    { "shmdt ", 67, "%d", 1, "%p"},
    { "msgget ", 68, "%d", 2, "%d, %d"},
    { "msgsnd ", 69, "%d", 4, "%d, %p, %l, %d"},
    { "msgrcv ", 70, "%l", 5, "%d, %p, %l, %l, %d"},
    { "msgctl ", 71, "%d", 3, "%d, %d, %p"},
    { "fcntl ", 72, "%d", 2, "%d, %d, ..."},
    { "flock ", 73, "%d", 2, "%d, %d"},
    { "fsync ", 74, "%d", 1, "%d"},
    { "fdatasync ", 75, "%d", 1, "%d"},
    { "truncate ", 76, "%d", 2, "%s, %d"},
    { "ftruncate ", 77, "%d", 2, "%d, %d"},
    { "getdents ", 78, "%d", 3, "%d, %p, %d"},
    { "getcwd ", 79, "%s", 2, "%s, %l"},
    { "chdir ", 80, "%d", 1, "%s"},
    { "fchdir ", 81, "%d", 1, "%d"},
    { "rename ", 82, "%d", 2, "%s, %s"},
    { "mkdir ", 83, "%d", 2, "%s, %d"},
    { "rmdir ", 84, "%d", 1, "%s"},
    { "creat ", 85, "%d", 2, "%s, %d"},
    { "link ", 86, "%d", 2, "%s, %s"},
    { "unlink ", 87, "%d", 1, "%s"},
    { "symlink ", 88, "%d", 2, "%s, %s"},
    { "readlink ", 89, "%l", 3, "%s, %s, %l"},
    { "chmod ", 90, "%d", 2, "%s, %d"},
    { "fchmod ", 91, "%d", 2, "%d, %d"},
    { "chown ", 92, "%d", 3, "%s, %d, %d"},
    { "fchown ", 93, "%d", 3, "%d, %d, %d"},
    { "lchown ", 94, "%d", 3, "%s, %d, %d"},
    { "umask ", 95, "%d", 1, "%d"},
    { "gettimeofday ", 96, "%d", 2, "%p, %p"},
    { "getrlimit ", 97, "%d", 2, "%d, %p"},
    { "getrusage ", 98, "%d", 2, "%d, %p"},
    { "sysinfo ", 99, "%d", 1, "%p"},
    { "times ", 100, "%l", 1, "%p"},
    { "ptrace ", 101, "%l", 4, "%d ,%d, %p, %p"},
    { "getuid ", 102, "%l",0, ""},
    { "syslog ", 103, "%d",3, "%d, %p, %d"},
    { "getgid ", 104, "%l", 0, ""},
    { "setuid ", 105, "%d", 1, "%p"},
    { "setgid ", 106, "%d",1, "%p"},
    { "geteuid ", 107, "%l", 0, ""},
    { "getegid ", 108, "%l", 0, ""},
    { "setpgid ", 109, "%d", 2, "%d, %d"},
    { "getppid ", 110, "%l", 0, ""},
    { "getpgrp ", 111, "%l", 0, ""},
    { "setsid ", 112, "%l", 0, ""},
    { "setreuid ", 113, "%d", 2 "%p, %p"},
    { "setregid ", 114, "%d", 2, "%p, %p"},
    { "getgroups ", 115, "%d", 2, "%d, %p"},
    { "setgroups ", 116, "%d", 2, "%d, %p"},
    { "setresuid ", 117, "%d", 3, "%p, %p, %p"},
    { "getresuid ", 118, "%d", 3, "%p, %p, %p"},
    { "setresgid ", 119, "%d", 3, "%p, %p, %p"},
    { "getresgid ", 120, "%d", 3, "%p, %p, %p"},
    { "getpgid ", 121, "%d", 1,"%d"},
    { "setfsuid ", 122, "%d", 1,"%p"},
    { "setfsgid ", 123, "%d", 1,"%p"},
    { "getsid ", 124, "%d", 1,"%d"},
    { "capget ", 125, "%d", 2, "%p, %p"},
    { "capset ", 126, "%d", 2, "%p, %p"},
    { "rt_sigpending ", 127, "%p", 1, "%p, %d"},
    { "rt_sigtimedwait ", 128, "%d", 3, "%p, %p, %p"},
    { "rt_sigqueueinfo ", 129, "%d", 3, "%d, %d, %p"},
    { "rt_sigsuspend ", 130, "%d", 1, "%p"},
    { "sigaltstack ", 131, "%d", 2, "%p, %p"},
    { "utime ", 132, "%d", 2, "%p, %p"},
    { "mknod ", 133, "%d", 2, "%p, %p"},
    { "uselib ", 134, "%d", 1, "%p"},
    { "personality ", 135, "%d", 1, "%p"},
    { "ustat ", 136, "%d", 2, "%p, %p"},
    { "statfs ", 137, "%d", 2, "%p, %p"},
    { "fstatfs ", 138, "%d", 2, "%d, %p"},
    { "sysfs ", 139, "%d", 1, "%d"},
    { "getpriority ", 140, "%d", 2, "%d, %d"},
    { "setpriority ", 141, "%d", 3, "%d, %d, %d"},
    { "sched_setparam ", 142, "%d", 2, "%d, %p"},
    { "sched_getparam ", 143, "%d", 2, "%d, %p"},
    { "sched_setscheduler ", 144, "%d", 3, "%d, %d, %p"},
    { "sched_getscheduler ", 145, "%d", 1, "%d"},
    {"sched_get_priority_max", 146, "%d", 1, "%d"},
    {"sched_get_priority_min", 147, "%d", 1, "%d"},
    {"sched_rr_get_interval", 148, "%d", 2, "%d, %p"},
    { "mlock ", 149, "%d", 2, "%p, %d"},
    { "munlock ", 150, "%d", 2, "%p, %d"},
    { "mlockall ", 151, "%d", 1, "%d"},
    { "munlockall ", 152, "%d", 0, ""},
    { "vhangup ", 153, %d, "%d", 0, ""},
    { "modify_ldt ", 154, "%d", 3, "%d, %p, %p"},
    { "pivot_root ", 155, "%d", 2, "%p, %p"},
    { "_sysctl ", 156, "%d", 1, "%p"},
    { "prctl ", 157, "%d", 5,"%d, %p, %p, %p, %p"},
    { "arch_prctl ", 158, "%d", 2, "%d, %p"},
    { "adjtimex ", 159, "%d", 1 "%d"},
    { "setrlimit ", 160, "%d", 2, "%d, %p"},
    { "chroot ", 161, "%d", 1, "%p"},
    { "sync ", 162, "%l", 0, ""},
    { "acct ", 163, "%d", 1, "%p"},
    { "settimeofday ", 164, "%d", 2, "%p, %p"},
    { "mount ", 165, "%d", 5, "%d, %p, %p, %p, %p"},
    { "umount2 ", 166, "%d", 2, "%p, %d"},
    { "swapon ", 167, "%d", 2, "%p, %d"},
    { "swapoff ", 168, "%d", 1, "%p"},
    { "reboot ", 169, "%d", 4, "%d, %d, %d, %p"},
    { "sethostname ", 170, "%d", 2, "%p, %d"},
    { "setdomainname ", 171, "%d", 2 "%p, %d"},
    { "iopl ", 172, "%d", 1, "%d"},
    { "ioperm ", 173, "%d", 3, "%d, %p, %p"},
    { "create_module ", 174, "%l", 2, "%p, %d"},
    { "init_module ", 175, "%d", 2, "%p, %p"},
    { "delete_module ", 176, "%d", 1, "%p"},
    { "get_kernel_syms ", 177, "%d", 1, "%p"},
    { "query_module ", 178, "%d", 5, "%p, %d, %p, %d, %d"},
    { "quotactl ", 179, "%l", 4, "%d, %p, %d, %p"},
    { "nfsservctl ", 180, "%x", 3, "%d, %p, %p"},
    { "getpmsg ", 181, "%d", 5, "%d, %p, %p, %p, %p"},
    { "putpmsg ", 182, "%d", 5, "%d, %p, %p, %d, %d"},
    { "afs_syscall ", 183, "%l", 6, "%p, %p, %p, %p, %p, %p"},
    { "tuxcall ", 184, "%d", 6, "%p, %p, %p, %p, %p, %p"},
    { "security ", 185, "%d", 6, "%p, %p, %p, %p, %p, %p"},
    { "gettid ", 186, "%d", 0, ""},
    { "readahead ", 187, "%d", 3, "%d, %p, %d"},
    { "setxattr ", 188, "%d", 5, "%p, %p, %p, %d, %d"},
    { "lsetxattr ", 189, "%d", 5, "%p, %p, %p, %d, %d"},
    { "fsetxattr ", 190, "%d", 5, "%p, %p, %p, %d, %d"},
    { "getxattr ", 191, "%d", 4, "%p, %p, %p, %d"},
    { "lgetxattr ", 192, "%d", 4, "%p, %p, %p, %d"},
    { "fgetxattr ", 193, "%d", 4, "%d, %p, %p, %d"},
    { "listxattr ", 194, "%d", 3, "%p, %p, %d"},
    { "llistxattr ", 195, "%d", 3, "%p, %p, %d"},
    { "flistxattr ", 196, "%d", 3, "%d, %p, %d"},
    { "removexattr ", 197, "%d", 2, "%p, %p"},
    { "lremovexattr ", 198, "%d", 2, "%p, %p"},
    { "fremovexattr ", 199, "%d", 2, "%d, %p"},
    { "tkill ", 200, "%d", 2, "%d, %d"},
    { "time ", 201, "%l", 1, "%d, %p, %d"},
    { "futex ", 202, "%d", 6, "%p, %d, %d, %p, %p, %d"},
    { "sched_setaffinity ", 203, "%d", 3, "%d, %d, %p"},
    { "sched_getaffinity ", 204, "%d", 3, "%d, %d, %p"},
    { "set_thread_area ", 205, "%d", 1, "%p"},
    { "io_setup ", 206, "%d", 2, "%p, %p"},
    { "io_destroy ", 207, "%d", 1, "%p"},
    { "io_getevents ", 208, "%d", 5, "%p, %p, %p, %p, %p"},
    { "io_submit ", 209, "%d", 3, "%p, %p, %p"},
    { "io_cancel ", 210, "%d", 3, "%p, %p, %p"},
    { "get_thread_area ", 211, "%d", 1, "%p"},
    { "lookup_dcookie ", 212, "%d", 3, "%p, %p, %d"},
    { "epoll_create ", 213, "%d", 1, "%d"},
    { "epoll_ctl_old ", 214, "%l", 6, "%p, %p, %p, %p, %p, %p"},
    { "epoll_wait_old ", 215, "%l", 6, "%p, %p, %p, %p, %p, %p"},
    { "remap_file_pages ", 216, "%d", 5, "%p, %d, %d, %d, %d"},
    { "getdents64 ", 217, "%d", 3, "%ui, %p, %ui"},
    { "set_tid_address ", 218, "%l", 1, "%p"},
    { "restart_syscall ", 219, "%l", 0, ""},
    { "semtimedop ", 220, "%d", 3, "%d, %p, %p"},
    { "fadvise64 ", 221, "%l", 4, "%d, %p, %p, %d"},
    { "timer_create ", 222, "%d", 3, "%p, %p, %p"},
    { "timer_settime ", 223, "%d", 4, "%p, %d, %p, %p"},
    { "timer_gettime ", 224, "%d", 2, "%p, %p"},
    { "timer_getoverrun ", 225, "%d", 1, "%p"},
    { "timer_delete ", 226, "%d", 1, "%p"},
    { "clock_settime ", 227, "%d", 2, "%p, %p"},
    { "clock_gettime ", 228, "%d", 2, "%p, %p"},
    { "clock_getres ", 229, "%d", 2, "%p, %p"},
    { "clock_nanosleep ", 230, "%d", 4, "%p, %d, %p, %p"},
    { "exit_group ", 231, "%l", 1, "%d"},
    { "epoll_wait ", 232, "%d", 4, "%d, %p, %p, %d"},
    { "epoll_ctl ", 233, "%d", 4, "%d, %d, %d, %p"},
    { "tgkill ", 234, "%d", 3, "%d, %d, %d"},
    { "utimes ", 235, "%d", 2, "%p, %p"},
    { "vserver ", 236, "%l", 6, "%p, %p, %p, %p, %p, %p"},
    { "mbind ", 237, "%d", 6, "%p, %p, %p, %p, %p, %p"},
    { "set_mempolicy ", 238, "%d", 3, "%d, %p, %p"},
    { "get_mempolicy ", 239, "%d", 5, "%p, %p, %p, %p, %p"},
    { "mq_open ", 240, "%l", 4, "%p ,%d, %p, %p"},
    { "mq_unlink ", 241, "%l", 1, "%p"},
    { "mq_timedsend ", 242, "%d", 4, "%p, %p, %d, %p"},
    { "mq_timedreceive ", 243, "%d", 4, "%p, %p, %d, %p"},
    { "mq_notify ", 244, "%l", 2, "%p, %p"},
    { "mq_getsetattr ", 245, "%l", 3, "%p, %p, %p"},
    { "kexec_load ", 246, "%l", 4, "%p, %p, %p, %p"},
    { "waitid ", 247, "%d", 4, "%p, %p, %p, %p"},
    { "add_key ", 248, "%l", 5, "%p, %p, %p, %p, %p"},
    { "request_key ", 249, "%l", 4, "%p, %p, %p, %p"},
    { "keyctl ", 250, "%l", 1, "%d, ..."},
    { "ioprio_set ", 251, "%d", 3, "%d, %d, %d"},
    { "ioprio_get ", 252, "%d", 2, "%d, %d"},
    { "inotify_init ", 253, "%d", 0, ""},
    { "inotify_add_watch ", 254, "%d", 3, "%d, %p, %p"},
    { "inotify_rm_watch ", 255, "%d", 2, "%d, %p"},
    { "migrate_pages ", 256, "%l", 6, "%p, %p, %p, %p, %p, %p"},
    { "openat ", 257, "%d", 4, "%p, %p, %p, %p"},
    { "mkdirat ", 258, "%d", 3, "%d, %p, %p"},
    { "mknodat ", 259, "%d", 4, "%p, %p, %p, %p"},
    { "fchownat ", 260, "%d", 5, "%d, %p, %p, %p, %d"},
    { "futimesat ", 261, "%d", 3, "%d, %p, %p"},
    { "newfstatat ", 262, "%l", 6, "%p, %p, %p, %p, %p, %p"},
    { "unlinkat ", 263, "%d", 3, "%d, %p, %d"},
    { "renameat ", 264, "%d", 4, "%d, %p, %d, %p"},
    { "linkat ", 265, "%d", 5, "%d, %p, %d, %p, %d"},
    { "symlinkat ", 266, "%d", 3, "%p, %d, %p"},
    { "readlinkat ", 267, "%d", 4, "%d, %p, %p, %d"},
    { "fchmodat ", 268, "%d", 4, "%d, %p, %p, %d"},
    { "faccessat ", 269, "%d", 4, "%d, %p, %d, %d"},
    { "pselect6 ", 270, "%d", 6, "%d, %p, %p, %p, %p, %p"},
    { "ppoll ", 271, "%d", 3, "%p, %p, %d"},
    { "unshare ", 272, "%d", 1, "%d"},
    { "set_robust_list ", 273, "%l", 2, "%p, %d"},
    { "get_robust_list ", 274, "%l", 3, "%d, %p, %d"},
    { "splice ", 275, "%d", 6, "%d, %p, %d, %p, %d, %ui"},
    { "tee ", 276, "%d", 4, "%d, %d, %d, %ui"},
    { "sync_file_range ", 277, "%d", 4, "%d, %p, %p, %ui"},
    { "vmsplice ", 278, "%d", 4, "%d, %p, %p, %ui"},
    { "move_pages ", 279, "%l", 6, "%d, %p, %p, %p, %d, %d"},
    { "utimensat ", 280, "%d", 4, "%d, %p, %p, %d"},
    { "epoll_pwait ", 281, "%d", 5, "%d, %p, %d, %d, %p"},
    { "signalfd ", 282, "%d", 3, "%d, %p, %d"},
    { "timerfd_create ", 283, "%d", 2, "%d, %d"},
    { "eventfd ", 284, "%d", 2, "%ui, %d"},
    { "fallocate ", 285, "%d", 4, "%d, %d, %p, %p"},
    { "timerfd_settime ", 286, "%d", 4, "%d, %d, %p, %p"},
    { "timerfd_gettime ", 287, "%d", 2, "%d, %p"},
    { "accept4 ", 288, "%d", 4, "%d, %p, %p, %d"},
    { "signalfd4 ", 289, "%d", 3, "%d, %p, %d"},
    { "eventfd2 ", 290, "%d", 2, "%ui, %d"},
    { "epoll_create1 ", 291, "%d", 1, "%d"},
    { "dup3 ", 292, "%d", 3, "%d, %d, %d"},
    { "pipe2 ", 293, "%d", 1, "%p"},
    { "inotify_init1 ", 294, "%d", 1, "%d"},
    { "preadv ", 295, "%l", 6, "%p, %p, %p, %p, %p, %p"},
    { "pwritev ", 296, "%l", 6, "%p, %p, %p, %p, %p, %p"},
    { "rt_tgsigqueueinfo ", 297, "%d", 6, "%p, %p, %p, %p, %p, %p"},
    { "perf_event_open ", 298, "%d", 6, "%p, %p, %p, %p, %p, %p"},
    { "recvmmsg ", 299, "%d", 6, "%p, %p, %p, %p, %p, %p"},
    { NULL, 0, NULL, 0, NULL}
  };
