/*
** syscall.h for syscall in /home/ss814/Documents/Epitech/TPs/STRACE/step2
**
** Made by Sampson SAVINEL
** Login   <ss814@epitech.net>
**
** Started on  Fri May  4 18:43:50 2012 Sampson SAVINEL
** Last update Wed May  9 18:31:04 2012 belia-_r
*/

#ifndef		__SYSCALL
# define	__SYSCALL


typedef struct s_syscall	t_syscall;


enum	e_type
  {
    CHAR = 1,
    SIGNED_CHAR,
    UNSIGNED_CHAR,
    POINTER_CHAR,
    SHORT,
    SHORT_INT,
    SIGNED_SHORT,
    SIGNED_SHORT_INT,
    UNSIGNED_SHORT,
    UNSIGNED_SHORT_INT,
    INT,
    SIGNED_INT,
    UNSIGNED,
    UNSIGNED_INT,
    LONG,
    LONG_INT,
    SIGNED_LONG,
    SIGNED_LONG_INT,
    UNSIGNED_LONG,
    UNSIGNED_LONG_INT,
    LONG_LONG,
    LONG_LONG_INT,
    SIGNED_LONG_LONG,
    SIGNED_LONG_LONG_INT,
    UNSIGNED_LONG_LONG,
    UNSIGNED_LONG_LONG_INT,
    FLOAT,
    DOUBLE,
    LONG_DOUBLE,
    POINTER,
    PPP
  };

struct		s_syscall
{
  char		*name;
  int		id;
  e_type	ret_type;
  e_type	*params;
};

t_syscall syscall_tab[] =
  {
    { "read ", 0, SIGNED_INT, {INT, POINTER, UNSIGNED_INT, NULL}},
    { "write ", 1 SIGNED_INT, {INT, POINTER, UNSIGNED_INT, NULL}},
    { "open ", 2, INT, {POINTER_CHAR, INT, INT, NULL}},
    { "close ", 3, INT, {INT, NULL}},
    { "stat ", 4, INT, {POINTER_CHAR, POINTER, NULL}},
    { "fstat ", 5, INT, {INT, POINTER, NULL}},
    { "lstat ", 6, INT, {POINTER_CHAR, POINTER, NULL}},
    { "poll ", 7, INT, {POINTER, UNSIGNED_LONG_INT, INT, NULL}},
    { "lseek ", 8, SIGNED_INT, {INT, SIGNED_INT, INT, NULL}},
    { "mmap ", 9, POINTER, {POINTER, UNSIGNED_INT, INT, INT, SIGNED_INT, NULL}},
    { "mprotect ", 10, INT, {POINTER, UNSIGNED_LONG_INT, INT, NULL}},
    { "munmap ", 11, INT, {POINTER, UNSIGNED_LONG_INT, NULL}},
    { "brk ", 12, INT, {POINTER, NULL}},
    { "rt_sigaction ", 13, INT, {INT, POINTER, POINTER, NULL}},
    { "rt_sigprocmask ", 14, INT, {INT, POINTER, POINTER, NULL}},
    { "rt_sigreturn ", 15, INT, {UNSIGNED_LONG, NULL}},
    { "ioctl ", 16, INT, {INT, INT, PPP, NULL}},
    { "pread64 ", 17, SIGNED_LONG_INT, {INT, POINTER, UNSIGNED_LONG, SIGNED_INT, NULL}},
    { "pwrite64 ", 18, SIGNED_LONG_INT, {INT, POINTER, UNSIGNED_LONG, SIGNED_INT, NULL}},
    { "readv ", 19, SIGNED_LONG_INT, {INT, POINTER, INT, NULL}},
    { "writev ", 20, SIGNED_LONG_INT, {INT, POINTER, INT, NULL}},
    { "access ", 21, INT, {POINTER_CHAR, INT, NULL}},
    { "pipe ", 22, INT, {INT, NULL}},
    { "select ", 23, INT, {INT, POINTER, POINTER, POINTER, POINTER, NULL}},
    { "sched_yield ", 24, INT, {NULL}},
    { "mremap ", 25, POINTER, {POINTER, UNSIGNED_LONG, UNSIGNED_LONG, INT, PPP, NULL}},
    { "msync ", 26, INT, {POINTER, UNSIGNED_LONG, INT, NULL}},
    { "mincore ", 27, INT, {POINTER, UNSIGNED_LONG, POINTER_CHAR, NULL}},
    { "madvise ", 28, INT, {POINTER, UNSIGNED_LONG, INT, NULL}},
    { "shmget ", 29, INT, {INT , UNSIGNED_LONG, INT, NULL}},
    { "shmat ", 30, POINTER, {INT, POINTER, INT, NULL}},
    { "shmctl ", 31, INT, {INT, INT, POINTER, NULL}},
    { "dup ", 32, INT, {INT, NULL}},
    { "dup2 ", 33, INT, {INT, INT, NULL}},
    { "pause ", 34, INT, {NULL}},
    { "nanosleep ", 35, INT, {POINTER, POINTER, NULL}},
    { "getitimer ", 36, INT, {INT, POINTER, NULL}},
    { "alarm ",	37, UNSIGNED_INT, {UNSIGNED_INT, NULL}},
    { "setitimer ", 38, INT, {INT, POINTER, POINTER, NULL}},
    { "getpid ", 39, INT, {NULL}},
    { "sendfile ", 40, SIGNED_LONG_INT, {INT, INT, SIGNED_INT, UNSIGNED_INT, NULL}},
    { "socket ", 41, INT, {INT, INT, INT, NULL}},
    { "connect ", 42, INT, {INT, POINTER, INT, NULL}},
    { "accept ", 43, INT, {INT, POINTER, POINTER, NULL}},
    { "sendto ", 44, SIGNED_LONG_INT, {INT, POINTER, UNSIGNED_LONG, INT, NULL}},
    { "recvfrom ", 45, SIGNED_LONG_INT, {INT, POINTER, UNSIGNED_LONG, INT, POINTER, POINTER, NULL}},
    { "sendmsg ", 46, SIGNED_LONG_INT, {INT, POINTER, INT, NULL}},
    { "recvmsg ", 47, SIGNED_LONG_INT, {INT, POINTER, INT, NULL}},
    { "shutdown ", 48, INT, {INT, INT, NULL}},
    { "bind ", 49, INT, {INT, POINTER, INT, NULL}},
    { "listen ", 50, INT, {INT, INT, NULL}},
    { "getsockname ", 51, INT, {INT, POINTER, POINTER, NULL}},
    { "getpeername ", 52, INT, {INT, POINTER, POINTER, NULL}},
    { "socketpair ", 53, INT, {INT, INT, INT, INT, NULL}},
    { "setsockopt ", 54, INT, {INT, INT, INT, POINTER, INT, NULL}},
    { "getsockopt ", 55, INT, {INT, INT, INT, POINTER, POINTER, NULL}},
    { "clone ", 56, INT, {POINTER, POINTER, INT, POINTER, PPP, NULL}},
    { "fork ", 57, INT, {NULL}},
    { "vfork ", 58, INT, {NULL}},
    { "execve ", 59, INT, {POINTER_CHAR, POINTER, POINTER, NULL}},
    { "exit ", 60, NULL, {INT, NULL}},
    { "wait4 ", 61, INT, {INT, POINTER, INT, POINTER, NULL}},
    { "kill ", 62, INT, {INT, INT, NULL}},
    { "uname ", 63, INT, {POINTER, NULL}},
    { "semget ", 64, INT, {INT, INT, INT, NULL}},
    { "semop ", 65, INT, {INT, POINTER, UNSIGNED, NULL}},
    { "semctl ", 66, INT, {INT, INT, INT, PPP, NULL}},
    { "shmdt ", 67, INT, {POINTER, NULL}},
    { "msgget ", 68, INT, {INT, INT, NULL}},
    { "msgsnd ", 69, INT, {INT, POINTER, UNSIGNED_LONG, INT, NULL}},
    { "msgrcv ", 70, SIGNED_LONG_INT, {INT, POINTER, UNSIGNED_LONG, LONG, INT, NULL}},
    { "msgctl ", 71, INT, {INT, INT, POINTER, NULL}},
    { "fcntl ", 72, INT, {INT, INT, PPP, NULL}},
    { "flock ", 73, INT, {INT, INT, NULL}},
    { "fsync ", 74, INT, {INT, NULL}},
    { "fdatasync ", 75, INT, {INT, NULL}},
    { "truncate ", 76, INT, {POINTER_CHAR, SIGNED_INT, NULL}},
    { "ftruncate ", 77, INT, {INT, SIGNED_INT, NULL}},
    { "getdents ", 78, INT, {UNSIGNED_INT, POINTER, UNSIGNED_INT, NULL}},
    { "getcwd ", 79, POINTER_CHAR, {POINTER_CHAR, UNSIGNED_LONG, NULL}},
    { "chdir ", 80, INT, {POINTER_CHAR, NULL}},
    { "fchdir ", 81, INT, {INT, NULL}},
    { "rename ", 82, INT, {POINTER_CHAR, POINTER_CHAR, NULL}},
    { "mkdir ", 83, INT, {POINTER_CHAR, UNSIGNED_INT, NULL}},
    { "rmdir ", 84, INT, {POINTER_CHAR, NULL}},
    { "creat ", 85, INT, {POINTER_CHAR, UNSIGNED_INT, NULL}},
    { "link ", 86, INT, {POINTER_CHAR, POINTER_CHAR NULL}},
    { "unlink ", 87, INT, {POINTER_CHAR, NULL}},
    { "symlink ", 88, INT, {POINTER_CHAR, POINTER_CHAR, NULL}},
    { "readlink ", 89, SIGNED_LONG_INT, {POINTER_CHAR, POINTER_CHAR, UNSIGNED_LONG, NULL}},
    { "chmod ", 90, INT, {POINTER_CHAR, UNSIGNED_INT, NULL}},
    { "fchmod ", 91, INT, {INT, UNSIGNED_INT, NULL}},
    { "chown ", 92, INT, {POINTER_CHAR, UNSIGNED_INT, UNSIGNED_INT, NULL}},
    { "fchown ", 93, INT, {INT, UNSIGNED_INT, UNSIGNED_INT, NULL}},
    { "lchown ", 94, INT, {POINTER_CHAR, UNSIGNED_INT, UNSIGNED_INT, NULL}},
    { "umask ", 95, UNSIGNED_INT, {UNSIGNED_INT, NULL}},
    { "gettimeofday ", 96, INT, {POINTER, POINTER, NULL}},
    { "getrlimit ", 97, INT, {INT, POINTER, NULL}},
    { "getrusage ", 98, INT, {INT, POINTER, NULL}},
    { "sysinfo ", 99, INT, {POINTER, NULL}},
    { "times ", 100, LONG, {POINTER, NULL}},
    { "ptrace ", 101, LONG, {INT ,INT, POINTER, POINTER, NULL}},

    { "getuid ", 102, INT, {INT, POINTER, INT, NULL}},
    { "syslog ", 103, INT, {INT, POINTER, INT, NULL}},
    { "getgid ", 104, INT, {INT, POINTER, INT, NULL}},
    { "setuid ", 105, INT, {INT, POINTER, INT, NULL}},
    { "setgid ", 106, INT, {INT, POINTER, INT, NULL}},
    { "geteuid ", 107, INT, {INT, POINTER, INT, NULL}},
    { "getegid ", 108, INT, {INT, POINTER, INT, NULL}},
    { "setpgid ", 109, INT, {INT, POINTER, INT, NULL}},
    { "getppid ", 110, INT, {INT, POINTER, INT, NULL}},
    { "getpgrp ", 111, INT, {INT, POINTER, INT, NULL}},
    { "setsid ", 112, INT, {INT, POINTER, INT, NULL}},
    { "setreuid ", 113, INT, {INT, POINTER, INT, NULL}},
    { "setregid ", 114, INT, {INT, POINTER, INT, NULL}},
    { "getgroups ", 115, INT, {INT, POINTER, INT, NULL}},
    { "setgroups ", 116, INT, {INT, POINTER, INT, NULL}},
    { "setresuid ", 117, INT, {INT, POINTER, INT, NULL}},
    { "getresuid ", 118, INT, {INT, POINTER, INT, NULL}},
    { "setresgid ", 119, INT, {INT, POINTER, INT, NULL}},
    { "getresgid ", 120, INT, {INT, POINTER, INT, NULL}},
    { "getpgid ", 121, INT, {INT, POINTER, INT, NULL}},
    { "setfsuid ", 122, INT, {INT, POINTER, INT, NULL}},
    { "setfsgid ", 123, INT, {INT, POINTER, INT, NULL}},
    { "getsid ", 124, INT, {INT, POINTER, INT, NULL}},
    { "capget ", 125, INT, {INT, POINTER, INT, NULL}},
    { "capset ", 126, INT, {INT, POINTER, INT, NULL}},
    { "rt_sigpending ", 127, INT, {INT, POINTER, INT, NULL}},
    { "rt_sigtimedwait ", 128, INT, {INT, POINTER, INT, NULL}},
    { "rt_sigqueueinfo ", 129, INT, {INT, POINTER, INT, NULL}},
    { "rt_sigsuspend ", 130, INT, {INT, POINTER, INT, NULL}},
    { "sigaltstack ", 131, INT, {INT, POINTER, INT, NULL}},
    { "utime ", 132, INT, {INT, POINTER, INT, NULL}},
    { "mknod ", 133, INT, {INT, POINTER, INT, NULL}},
    { "uselib ", 134, INT, {INT, POINTER, INT, NULL}},
    { "personality ", 135, INT, {INT, POINTER, INT, NULL}},
    { "ustat ", 136, INT, {INT, POINTER, INT, NULL}},
    { "statfs ", 137, INT, {INT, POINTER, INT, NULL}},
    { "fstatfs ", 138, INT, {INT, POINTER, INT, NULL}},
    { "sysfs ", 139, INT, {INT, POINTER, INT, NULL}},
    { "getpriority ", 140, INT, {INT, POINTER, INT, NULL}},
    { "setpriority ", 141, INT, {INT, POINTER, INT, NULL}},
    { "sched_setparam ", 142, INT, {INT, POINTER, INT, NULL}},
    { "sched_getparam ", 143, INT, {INT, POINTER, INT, NULL}},
    { "sched_setscheduler ", 144, INT, {INT, POINTER, INT, NULL}},
    { "sched_getscheduler ", 145, INT, {INT, POINTER, INT, NULL}},
    { "mlock ", 149, INT, {INT, POINTER, INT, NULL}},
    { "munlock ", 150, INT, {INT, POINTER, INT, NULL}},
    { "mlockall ", 151, INT, {INT, POINTER, INT, NULL}},
    { "munlockall ", 152, INT, {INT, POINTER, INT, NULL}},
    { "vhangup ", 153, INT, {INT, POINTER, INT, NULL}},
    { "modify_ldt ", 154, INT, {INT, POINTER, INT, NULL}},
    { "pivot_root ", 155, INT, {INT, POINTER, INT, NULL}},
    { "_sysctl ", 156, INT, {INT, POINTER, INT, NULL}},
    { "prctl ", 157, INT, {INT, POINTER, INT, NULL}},
    { "arch_prctl ", 158, INT, {INT, POINTER, INT, NULL}},
    { "adjtimex ", 159, INT, {INT, POINTER, INT, NULL}},
    { "setrlimit ", 160, INT, {INT, POINTER, INT, NULL}},
    { "chroot ", 161, INT, {INT, POINTER, INT, NULL}},
    { "sync ", 162, INT, {INT, POINTER, INT, NULL}},
    { "acct ", 163, INT, {INT, POINTER, INT, NULL}},
    { "settimeofday ", 164, INT, {INT, POINTER, INT, NULL}},
    { "mount ", 165, INT, {INT, POINTER, INT, NULL}},
    { "umount2 ", 166, INT, {INT, POINTER, INT, NULL}},
    { "swapon ", 167, INT, {INT, POINTER, INT, NULL}},
    { "swapoff ", 168, INT, {INT, POINTER, INT, NULL}},
    { "reboot ", 169, INT, {INT, POINTER, INT, NULL}},
    { "sethostname ", 170, INT, {INT, POINTER, INT, NULL}},
    { "setdomainname ", 171, INT, {INT, POINTER, INT, NULL}},
    { "iopl ", 172, INT, {INT, POINTER, INT, NULL}},
    { "ioperm ", 173, INT, {INT, POINTER, INT, NULL}},
    { "create_module ", 174, INT, {INT, POINTER, INT, NULL}},
    { "init_module ", 175, INT, {INT, POINTER, INT, NULL}},
    { "delete_module ", 176, INT, {INT, POINTER, INT, NULL}},
    { "get_kernel_syms ", 177, INT, {INT, POINTER, INT, NULL}},
    { "query_module ", 178, INT, {INT, POINTER, INT, NULL}},
    { "quotactl ", 179, INT, {INT, POINTER, INT, NULL}},
    { "nfsservctl ", 180, INT, {INT, POINTER, INT, NULL}},
    { "getpmsg ", 181, INT, {INT, POINTER, INT, NULL}},
    { "putpmsg ", 182, INT, {INT, POINTER, INT, NULL}},
    { "afs_syscall ", 183, INT, {INT, POINTER, INT, NULL}},
    { "tuxcall ", 184, INT, {INT, POINTER, INT, NULL}},
    { "security ", 185, INT, {INT, POINTER, INT, NULL}},
    { "gettid ", 186, INT, {INT, POINTER, INT, NULL}},
    { "readahead ", 187, INT, {INT, POINTER, INT, NULL}},
    { "setxattr ", 188, INT, {INT, POINTER, INT, NULL}},
    { "lsetxattr ", 189, INT, {INT, POINTER, INT, NULL}},
    { "fsetxattr ", 190, INT, {INT, POINTER, INT, NULL}},
    { "getxattr ", 191, INT, {INT, POINTER, INT, NULL}},
    { "lgetxattr ", 192, INT, {INT, POINTER, INT, NULL}},
    { "fgetxattr ", 193, INT, {INT, POINTER, INT, NULL}},
    { "listxattr ", 194, INT, {INT, POINTER, INT, NULL}},
    { "llistxattr ", 195, INT, {INT, POINTER, INT, NULL}},
    { "flistxattr ", 196, INT, {INT, POINTER, INT, NULL}},
    { "removexattr ", 197, INT, {INT, POINTER, INT, NULL}},
    { "lremovexattr ", 198, INT, {INT, POINTER, INT, NULL}},
    { "fremovexattr ", 199, INT, {INT, POINTER, INT, NULL}},
    { "tkill ", 200, INT, {INT, POINTER, INT, NULL}},
    { "time ", 201, INT, {INT, POINTER, INT, NULL}},
    { "futex ", 202, INT, {INT, POINTER, INT, NULL}},
    { "sched_setaffinity ", 203, INT, {INT, POINTER, INT, NULL}},
    { "sched_getaffinity ", 204, INT, {INT, POINTER, INT, NULL}},
    { "set_thread_area ", 205, INT, {INT, POINTER, INT, NULL}},
    { "io_setup ", 206, INT, {INT, POINTER, INT, NULL}},
    { "io_destroy ", 207, INT, {INT, POINTER, INT, NULL}},
    { "io_getevents ", 208, INT, {INT, POINTER, INT, NULL}},
    { "io_submit ", 209, INT, {INT, POINTER, INT, NULL}},
    { "io_cancel ", 210, INT, {INT, POINTER, INT, NULL}},
    { "get_thread_area ", 211, INT, {INT, POINTER, INT, NULL}},
    { "lookup_dcookie ", 212, INT, {INT, POINTER, INT, NULL}},
    { "epoll_create ", 213, INT, {INT, POINTER, INT, NULL}},
    { "epoll_ctl_old ", 214, INT, {INT, POINTER, INT, NULL}},
    { "epoll_wait_old ", 215, INT, {INT, POINTER, INT, NULL}},
    { "remap_file_pages ", 216, INT, {INT, POINTER, INT, NULL}},
    { "getdents64 ", 217, INT, {INT, POINTER, INT, NULL}},
    { "set_tid_address ", 218, INT, {INT, POINTER, INT, NULL}},
    { "restart_syscall ", 219, INT, {INT, POINTER, INT, NULL}},
    { "semtimedop ", 220, INT, {INT, POINTER, INT, NULL}},
    { "fadvise64 ", 221, INT, {INT, POINTER, INT, NULL}},
    { "timer_create ", 222, INT, {INT, POINTER, INT, NULL}},
    { "timer_settime ", 223, INT, {INT, POINTER, INT, NULL}},
    { "timer_gettime ", 224, INT, {INT, POINTER, INT, NULL}},
    { "timer_getoverrun ", 225, INT, {INT, POINTER, INT, NULL}},
    { "timer_delete ", 226, INT, {INT, POINTER, INT, NULL}},
    { "clock_settime ", 227, INT, {INT, POINTER, INT, NULL}},
    { "clock_gettime ", 228, INT, {INT, POINTER, INT, NULL}},
    { "clock_getres ", 229, INT, {INT, POINTER, INT, NULL}},
    { "clock_nanosleep ", 230, INT, {INT, POINTER, INT, NULL}},
    { "exit_group ", 231, INT, {INT, POINTER, INT, NULL}},
    { "epoll_wait ", 232, INT, {INT, POINTER, INT, NULL}},
    { "epoll_ctl ", 233, INT, {INT, POINTER, INT, NULL}},
    { "tgkill ", 234, INT, {INT, POINTER, INT, NULL}},
    { "utimes ", 235, INT, {INT, POINTER, INT, NULL}},
    { "vserver ", 236, INT, {INT, POINTER, INT, NULL}},
    { "mbind ", 237, INT, {INT, POINTER, INT, NULL}},
    { "set_mempolicy ", 238, INT, {INT, POINTER, INT, NULL}},
    { "get_mempolicy ", 239, INT, {INT, POINTER, INT, NULL}},
    { "mq_open ", 240, INT, {INT, POINTER, INT, NULL}},
    { "mq_unlink ", 241, INT, {INT, POINTER, INT, NULL}},
    { "mq_timedsend ", 242, INT, {INT, POINTER, INT, NULL}},
    { "mq_timedreceive ", 243, INT, {INT, POINTER, INT, NULL}},
    { "mq_notify ", 244, INT, {INT, POINTER, INT, NULL}},
    { "mq_getsetattr ", 245, INT, {INT, POINTER, INT, NULL}},
    { "kexec_load ", 246, INT, {INT, POINTER, INT, NULL}},
    { "waitid ", 247, INT, {INT, POINTER, INT, NULL}},
    { "add_key ", 248, INT, {INT, POINTER, INT, NULL}},
    { "request_key ", 249, INT, {INT, POINTER, INT, NULL}},
    { "keyctl ", 250, INT, {INT, POINTER, INT, NULL}},
    { "ioprio_set ", 251, INT, {INT, POINTER, INT, NULL}},
    { "ioprio_get ", 252, INT, {INT, POINTER, INT, NULL}},
    { "inotify_init ", 253, INT, {INT, POINTER, INT, NULL}},
    { "inotify_add_watch ", 254, INT, {INT, POINTER, INT, NULL}},
    { "inotify_rm_watch ", 255, INT, {INT, POINTER, INT, NULL}},
    { "migrate_pages ", 256, INT, {INT, POINTER, INT, NULL}},
    { "openat ", 257, INT, {INT, POINTER, INT, NULL}},
    { "mkdirat ", 258, INT, {INT, POINTER, INT, NULL}},
    { "mknodat ", 259, INT, {INT, POINTER, INT, NULL}},
    { "fchownat ", 260, INT, {INT, POINTER, INT, NULL}},
    { "futimesat ", 261, INT, {INT, POINTER, INT, NULL}},
    { "newfstatat ", 262, INT, {INT, POINTER, INT, NULL}},
    { "unlinkat ", 263, INT, {INT, POINTER, INT, NULL}},
    { "renameat ", 264, INT, {INT, POINTER, INT, NULL}},
    { "linkat ", 265, INT, {INT, POINTER, INT, NULL}},
    { "symlinkat ", 266, INT, {INT, POINTER, INT, NULL}},
    { "readlinkat ", 267, INT, {INT, POINTER, INT, NULL}},
    { "fchmodat ", 268, INT, {INT, POINTER, INT, NULL}},
    { "faccessat ", 269, INT, {INT, POINTER, INT, NULL}},
    { "pselect6 ", 270, INT, {INT, POINTER, INT, NULL}},
    { "ppoll ", 271, INT, {INT, POINTER, INT, NULL}},
    { "unshare ", 272, INT, {INT, POINTER, INT, NULL}},
    { "set_robust_list ", 273, INT, {INT, POINTER, INT, NULL}},
    { "get_robust_list ", 274, INT, {INT, POINTER, INT, NULL}},
    { "splice ", 275, INT, {INT, POINTER, INT, NULL}},
    { "tee ", 276, INT, {INT, POINTER, INT, NULL}},
    { "sync_file_range ", 277, INT, {INT, POINTER, INT, NULL}},
    { "vmsplice ", 278, INT, {INT, POINTER, INT, NULL}},
    { "move_pages ", 279, INT, {INT, POINTER, INT, NULL}},
    { "utimensat ", 280, INT, {INT, POINTER, INT, NULL}},
    { "epoll_pwait ", 281, INT, {INT, POINTER, INT, NULL}},
    { "signalfd ", 282, INT, {INT, POINTER, INT, NULL}},
    { "timerfd_create ", 283, INT, {INT, POINTER, INT, NULL}},
    { "eventfd ", 284, INT, {INT, POINTER, INT, NULL}},
    { "fallocate ", 285, INT, {INT, POINTER, INT, NULL}},
    { "timerfd_settime ", 286, INT, {INT, POINTER, INT, NULL}},
    { "timerfd_gettime ", 287, INT, {INT, POINTER, INT, NULL}},
    { "accept4 ", 288, INT, {INT, POINTER, INT, NULL}},
    { "signalfd4 ", 289, INT, {INT, POINTER, INT, NULL}},
    { "eventfd2 ", 290, INT, {INT, POINTER, INT, NULL}},
    { "epoll_create1 ", 291, INT, {INT, POINTER, INT, NULL}},
    { "dup3 ", 292, INT, {INT, POINTER, INT, NULL}},
    { "pipe2 ", 293, INT, {INT, POINTER, INT, NULL}},
    { "inotify_init1 ", 294, INT, {INT, POINTER, INT, NULL}},
    { "preadv ", 295, INT, {INT, POINTER, INT, NULL}},
    { "pwritev ", 296, INT, {INT, POINTER, INT, NULL}},
    { "rt_tgsigqueueinfo ", 297, INT, {INT, POINTER, INT, NULL}},
    { "perf_event_open ", 298, INT, {INT, POINTER, INT, NULL}},
    { "recvmmsg ", 299, INT, {INT, POINTER, INT, NULL}},
    { "fanotify_init ", 300, INT, {INT, POINTER, INT, NULL}},
    { "fanotify_mark ", 301, INT, {INT, POINTER, INT, NULL}},
    { "prlimit64 ", 302, INT, {INT, POINTER, INT, NULL}},
    { "name_to_handle_at ", 303, INT, {INT, POINTER, INT, NULL}},
    { "open_by_handle_at ", 304, INT, {INT, POINTER, INT, NULL}},
    { "clock_adjtime ", 305, INT, {INT, POINTER, INT, NULL}},
    { "sendmmsg ", 307, INT, {INT, POINTER, INT, NULL}},
    { "setns ", 308, INT, {INT, POINTER, INT, NULL}},
    { NULL, 0}
  };

#endif		//SYSCALL
