######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 17 19:29:54 2011
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ..

# Input
HEADERS += QTDisplay.hh Scene.hh
SOURCES += QTDisplay.cpp Scene.cpp
